### ISSUE TITLE
Фильтр на странице /whdb/

### ISSUE THREAD

**Issue by Gamer-Grad** [minlexx/whdbx_web#19]
Было бы интересно если бы появилась возможность фильтрации систем по наличию тех. или прочих планет.

**Comment by minlexx** [comment]
Для чего? Для планетарки?

**Comment by minlexx** [comment]
Прямо скажу, вряд ли я буду это делать. Сайт - информер по ВХшкам, а не база данных по планетарке.

**Comment by minlexx** [comment]
Подробнее поясню, почему - это технчески сложно осуществить ради весьма малой выгоды. 

Таблица, по которой работают запросы из страницы  /whdb/ не содержит никаких данных о планетах. Вообще нету такой таблицы, в которой бы удобно лежали данные о планетах в системе. Есть большая таблица из EVE SDE, mapDenormalize, в которой лежат вообще все небесные тела (celestials) всех солнечных систем с их именами и и координатами. Вот если из неё извлечь все небесные тела определенной системы, отфильтровать из них те что являются планетами, тогда можно получить список имен планет. В именах планет указан их тип, наподобие `Planet (Lava)` из которого надо ещё вырезать то, что в скобках, и тогда будет тип планеты ясен. Как по всему этому делу фильтрануть одним запросом - хрен его знает, да и не очень надо это в целом. Чтобы было удобно искать по типам планет, надо переработать базу ВХшек (вот эту - https://github.com/minlexx/whdbx_web/blob/master/db/sqlite_sql/wormholesystems_new.sql) так чтобы в ней был столбец с типами планет, или по столбцу на каждый тип планеты с их количеством, ну в общем гора работы, выглядит нерациональной тратой времени.

Вот код который извлекает данные о планетах для текущей ВХшки - https://github.com/minlexx/whdbx_web/blob/master/classes/database.py#L192 и это уже больше лимитов времени и кода, чем я готов потратить ради планетарки.

**Comment by Gamer-Grad** [comment]
Я гляну их, может чего придумаю :)

**Comment by MicronHeleneto** [comment]
Сделать нужный запрос можно, но проблема будет в другом. 
1. Реальный доход планетарки зависит еще и от концентрации ресурсов на планетах. Я раньше думал, что чем выше класс ВХ, тем богаче планеты, но оказалось не совсем так... Есть бедные планеты в С5, а есть богатые в С1. И этой информации нет в SDE. Поэтому даже EvePlanetaryPlanner имеет специальные "бегунки", которыми для расчета индекса развития по каждому ресурсу надо выставить концентрации ресурсов именно под свои планеты. Просто подобрать ВХ с нужным списком планет недостаточно.
2. Целесообразность? Когда ты вошел в новую ВХ, ты можешь посмотреть, какие тут планеты. Это полезная инфа. Но как использовать инфу о том, что нужный мне набор планет есть именно в J123456? Да в эту ВХ можно и не открыться никогда... Толку что она есть... Вот к примеру ты можешь воспользоваться сайтом, который позволяет выполнить такую операцию: ( http://www.eveplanets.com/eve/planet/set?planets_set=Barren%2CGas%2CIce%2COceanic%2CStorm%2CTemperate%2CLava%2CPlasma ) существует всего одна ВХ, содержащая все типы планет: J154735 - как эта информация может помочь планетарщику-любителю? :)

**Comment by Gamer-Grad** [comment]
Согласен, что задача не имеет смысла скорее всего.
