### ISSUE TITLE
С килборды нет данных

### ISSUE THREAD

**Issue by Gamer-Grad** [minlexx/whdbx_web#20]
Борда перестала загружаться на страницах...

**Comment by minlexx** [comment]
значит опять zkb чето поломали у себя в апи, такое бывало уже, и не раз
разберемся

**Comment by minlexx** [comment]
Они вообще поломали всё, теперь возвращают только id килла и никаких данных о нем.
Теперь это узнать можно только из EVE API, и на каждый килл вероятно придется делать отдельный запрос.

Предыстория: раньше один запрос на zkb решал проблему - у тебя сразу есть все данные о килле.

Потом  со временем ЗКБ убрало из выдачи информацию об именах - нету имени чара, альянса, корпы, корабля итд. только ID оставили, заставляя получать эту инфу отдельно... Блок киллов с ЗКБ стал грузиться в 5 раз дольше и я переделал его  в асинхронный, чтобы инфо о системе грузилось сразу, а киллы подтягивались со временем.

Теперь они пошли ещё дальше - убрали к херам вообще всю инфу из килла, оставив только его ID. Теперь придется на каждый из 30 киллов отдельно запрашивать всю инфу через ESI, это рассчитывай по 2-5 сек на запрос, значит блок с киллами будет грузиться первый раз (до кеширования) секунд 150 (2.5 минуты) это нормально вообще?

**Comment by Gamer-Grad** [comment]
Я пока что просто убрал это https://github.com/Gamer-Grad/whdbx_web/commit/d1f86a7437219100ccabd03ffad327a6ab596499

Сидел читал свогер на предмет как получить киллмейл

**Comment by minlexx** [comment]
За выходные починю, может и раньше (сегодня)

**Comment by minlexx** [comment]
Оп-оп, https://eve-wh.space/
медленно, но верно, киллы грузятся. Наверняка не всё успел починить, если ещё баги будут надо будет доделывать...

**Comment by minlexx** [comment]
С киллбордой-то вроде всё работает, надо будет ещё обновить БД до свежей версии, чтобы Drekavac и прочие новые триглавианы определялись (либо сделать чтобы названия неизвестных/новых типов тоже подтягивались из апи)
