### ISSUE TITLE
 Upgraded Avenger - Signature

### ISSUE THREAD

**Issue by Gamer-Grad** [minlexx/whdbx_web#22]
Upgraded Avenger - скорее всего имеет сигнатуру 3 000 метров, а не 30 000. Проверялось стрельбой из XL Cruise Missile, с учетом резистов, скорости и сигнатуры взрыва, урон получается как раз близкий на урон по цели сигнатурой около 3 000 метров.

**Comment by minlexx** [comment]
надо в других источниках посмотреть, щас..
раньше был ресурс, который путем расковыривания файлов клиента (я думаю) показывал статы вообще всех НПЦ, яоттуда брал статы по этому слиперу - http://playground.schildwall.info/basics/types/types.php?typeID=37472
но щас его нет (

**Comment by minlexx** [comment]
http://games.chruker.dk/eve_online/item.php?type_id=37472
```
Signature Radius:
30,000 m 
```
 говорят
