### ISSUE TITLE
Solar System 010366

### ISSUE THREAD

**Issue by Gamer-Grad** [minlexx/whdbx_web#27]
В системе есть как минимум 1 статик W237, при перехлопе сразу же открывается новый.

**Comment by minlexx** [comment]
:ok_hand: , Fixed with https://github.com/minlexx/whdbx_web/commit/2f2ebb3b4e341ece1d33e08e1506fa4760384314
Один статик - хорошо, но должен быть ещё один статик..)

**Comment by Gamer-Grad** [comment]
там возможно их 3 вообще C008, K346, W237

**Comment by minlexx** [comment]
Скорее всего C008 просто рандомная блуждайка фригатка в с5, у всех "соседних" систем по статика, и второй как раз K346

**Comment by minlexx** [comment]
Хотя, чего ждать, обновлю сейчас - https://eve-wh.space/J010366
Спасибо!
