### ISSUE TITLE
Время заполнения вентуры и время уборки облака

### ISSUE THREAD

**Issue by kemsta** [minlexx/whdbx_web#29]
> Время заполнения Вентуры с 2 x Gas Cloud Harvester II, Mining Frigate V, без бонусов на копку = 31 минут.

Это подпись сейчас кажется не актуальной, т.к. это время будет одинаково для всех сигнатур. Но полезным было бы посчитать время уборки облака той же самой вентурой

**Comment by minlexx** [comment]
это можно наверное, выглядит как просто поделить объем облака на объем вентуры и помножить на время заполнения, и вывести для каждого облака?)

**Comment by kemsta** [comment]
Наверное этого будет достаточно)
Добавил здесь https://github.com/minlexx/whdbx_web/pull/30
Автолинк почему-то не сработал
