### ISSUE TITLE
Кто живет в этой системе

### ISSUE THREAD

**Issue by kemsta** [minlexx/whdbx_web#31]
Очень полезно было бы иметь предположение какая корпа живет в вх.

В грубом приближении это можно предположить по килам на ZKB и простому принципу вроде "кто за последний месяц засветился несколько раз".
Идеально было бы при этом показать какие цитки есть в системе, но кажется esi не дает эту инфу.

**Comment by minlexx** [comment]
В первых версиях сайта был счетчик, рейтинг по убыванию, какая корпа чаще всего светилась в киллах (жертвы + аттакеры), и эта инфа выводилась отдельно, но при переезде на ESI там что-то пошло не так и эту штуку я выпилил. В принципе приблизительно и так по КБ прикинуть можно, для этого она и выводится, а достоверности от этой инфы всё равно никакой. Для прямо-таки полного статичтического анализа надо скачивать историю КБ примерно за год, ну хотя бы несколько месяцев, но у zkb одно время были анальные ограничения на это дело. Можно попробовать через ESI это как-то разрулить, ну или домучать zkb

**Comment by kemsta** [comment]
Помню, что я где-то раньше видел эту фичу и она была полезной. Возможно это был whdb) Не достоверной, но все же полезной. Если ее обогатить инфой о хозяевах цитадели, то она бы стала более полезной.
Попробую исследовать эту возможность и вернусь если получится

**Comment by kemsta** [comment]
В апи видны только те цитадели, в которые у тебя есть право дока, т.е. реализовать такое пока нельзя. Грустно, а очень хотелось бы эту фичу. Закрой если считаешь нужным или может быть все же захочешь реализовать по анализу кб?
